title: Ana Solorza
email: asolorza@fourthfruit.com 
description: >- # this means to ignore newlines until "baseurl:"
  Pre-Med, Biology junior at Chapman University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ana.fourthfruit.com" # the base hostname & protocol for your site, e.g. http://example.com
github: [metadata]

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed